---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: discord
  namespace: flux-system
spec:
  channel: flux-notifications
  secretRef:
    name: discord-url
  type: discord
