---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vpa-release
  namespace: flux-system
spec:
  chart:
    spec:
      chart: vertical-pod-autoscaler
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: vpa-repo
  interval: 1m0s
  storageNamespace: default
  targetNamespace: default
